### ISSUE TITLE
Composite word creator should exclude closed word classes

### ISSUE THREAD

**Issue by vthorsteinsson** [vthorsteinsson/Reynir#19]
Composite word generator should not create new conjunctions ('samtengingar') or other definitely closed word classes. For example, 'Bellen' should not be construed as 'Bell-en' where 'en' is a conjunction.

**Comment by busla** [comment]
oops, referenced the wrong issue. This was meant for #40

**Comment by vthorsteinsson** [comment]
This has been fixed in https://github.com/vthorsteinsson/ReynirPackage.
