### ISSUE TITLE
ordfl and fl fields in ord table need a larger varchar value

### ISSUE THREAD

**Issue by busla** [vthorsteinsson/Reynir#39]
got an error when importing ord.csv:

```
ERROR:  value too long for type character varying(16)
CONTEXT:  COPY ord, line 155, column ordfl: "nafnháttarmerki),"
```

_nafnháttarmerki_ is 15 chars long so it should have been imported properly.

Changed to `varchar(20)` and successfully imported _ord.csv_

https://github.com/busla/Reynir/commit/708d680378e19063cd321a8b778cba15049ef42f#diff-f94887202ef9aceae03b95bf25704909

**Comment by vthorsteinsson** [comment]
This is an error in the source data (or more correctly, in the importer). "nafnháttarmerki" should be "nhm".

**Comment by busla** [comment]
ok, so the https://github.com/vthorsteinsson/Reynir/blob/master/utils/external_data_validator.py is not importing it correctly?

**Comment by vthorsteinsson** [comment]
No. You need to make it a special case in the importer. By the way, this is only one word ('að').

**Comment by busla** [comment]
I´m not following. 

There are 15 lines that contain the word _nafnháttarmerki_ in SHsnid.csv. Where should I check for _að_ ?

**Comment by busla** [comment]
I see this line in obeyg.smaord.txt:

`að ao fs st nhm`

**Comment by vthorsteinsson** [comment]
OK, maybe I'm misunderstanding. The importer is trying to squeeze the word "nafnháttarmerki" into the ordfl column. I thought this was because somewhere the data had 'nafnháttarmerki' instead of the 'nhm' abbreviation. But maybe instead the data has a fault somewhere that causes the actual WORD "nafnháttarmerki" to appear in the ordfl column instead of the stofn or ordmynd columns? Missing commas or something?

**Comment by busla** [comment]
From line 3472227 in _SHsnid.csv_:
```
nafnháttarmerki;50422;hk;alm;nafnháttarmerki;NFET
nafnháttarmerki;50422;hk;alm;nafnháttarmerkið;NFETgr
nafnháttarmerki;50422;hk;alm;nafnháttarmerki;ÞFET
nafnháttarmerki;50422;hk;alm;nafnháttarmerkið;ÞFETgr
nafnháttarmerki;50422;hk;alm;nafnháttarmerki;ÞGFET
nafnháttarmerki;50422;hk;alm;nafnháttarmerkinu;ÞGFETgr
nafnháttarmerki;50422;hk;alm;nafnháttarmerkis;EFET
nafnháttarmerki;50422;hk;alm;nafnháttarmerkisins;EFETgr
nafnháttarmerki;50422;hk;alm;nafnháttarmerki;NFFT
nafnháttarmerki;50422;hk;alm;nafnháttarmerkin;NFFTgr
nafnháttarmerki;50422;hk;alm;nafnháttarmerki;ÞFFT
nafnháttarmerki;50422;hk;alm;nafnháttarmerkin;ÞFFTgr
nafnháttarmerki;50422;hk;alm;nafnháttarmerkjum;ÞGFFT
nafnháttarmerki;50422;hk;alm;nafnháttarmerkjunum;ÞGFFTgr
nafnháttarmerki;50422;hk;alm;nafnháttarmerkja;EFFT
nafnháttarmerki;50422;hk;alm;nafnháttarmerkjanna;EFFTgr
```

**Comment by vthorsteinsson** [comment]
Yup. But for these 15 rows, 'ordfl' is 'hk'. 'stofn' is 'nafnháttarmerki' and 'ordmynd' is the 15 different word forms. This cannot be the origin of the complaint about the 'ordfl' column being too small.

**Comment by vthorsteinsson** [comment]
Can you post line 155 of ord.csv? That is where the error is, apparently.

**Comment by busla** [comment]
I saw nothing problematic with that line in the beginning, but here it is:
```
[110] þrír;999012;to;alm;þrír;KK_NFFT
[111] þrír;999012;to;alm;þrjá;KK_ÞFFT
[112] þrír;999012;to;alm;þremur;KK_ÞGFFT
[113] þrír;999012;to;alm;þrem;KK_ÞGFFT2
[114] þrír;999012;to;alm;þriggja;KK_EFFT
[115] þrír;999012;to;alm;þrjár;KVK_NFFT
[116] þrír;999012;to;alm;þrjár;KVK_ÞFFT
[117] þrír;999012;to;alm;þremur;KVK_ÞGFFT
...
```

**Comment by vthorsteinsson** [comment]
There was a bug in the importer code. Case closed.
