### ISSUE TITLE
Api endpoint for articles not in db

### ISSUE THREAD

**Issue by pallih** [vthorsteinsson/Reynir#50]
I would love for the article.api endpoint to be expanded to parse a url, even though it isn't on a domain that http://greynir.is monitors.

The specific usecase I have in mind (for me), is entity extraction for http://umsagnir.gogn.in

Here's an example from the greynir.is web:

https://greynir.is/page?url=http%3A%2F%2Fumsagnir.gogn.in%2Fthing%2F146%2Fthingmal%2F80%2Fumsagnir%2F155

So a post request with either a url or text, return: json.

**Comment by vthorsteinsson** [comment]
Just between you and me, the code already implements an (alpha status) API called parse.api that has the same interface as postag.api. I.e., it accepts text via HTTP GET or POST, in the latter case either text/plain or form/url-encoded. It returns JSON with the parse trees corresponding to each sentence, or an error indicator if the sentence couldn't be parsed. See code at main.py, around line 407 and onwards. The plan is to allow simpler, more standard tree formats to be returned in the future. Any input and feedback is appreciated. - And note that parsing long texts can take time.
