### ISSUE TITLE
discrepancy when analysing "íslendingur" and "íslendingar"

### ISSUE THREAD

**Issue by busla** [vthorsteinsson/Reynir#53]
```json
      {
        "b": "NFFT", 
        "c": "kk", 
        "f": "alm", 
        "k": "WORD", 
        "s": "Íslendingur", 
        "t": "no_ft_nf_kk", 
        "x": "Íslendingar"
      },
```

```json
      {
        "b": "NFFT", 
        "c": "kvk", 
        "f": "alm", 
        "k": "WORD", 
        "s": "ís-lending", 
        "t": "no_ft_nf_kvk", 
        "x": "íslendingar"
      },
```

**Comment by busla** [comment]
To debug, the full sentence is obviously needed :)

Will post soon.

**Comment by vthorsteinsson** [comment]
"Íslendingar" is the correct spelling. "íslendingar" is incorrect spelling, so the word is not found in BÍN and Greynir tries to understand it as a composite word: "ís-lendingar" which means "landings on ice" :-)  "Flugmennirnir æfðu íslendingar á frosnu vatninu." So this is technically not a bug. We might however add support for commonly misspelled words, allowing them to be correctly categorized in the grammar but red-marked in output.
