### ISSUE TITLE
Location/address detection

### ISSUE THREAD

**Issue by sveinbjornt** [vthorsteinsson/Reynir#58]
It would be cool if Reynir identified place names and addresses in text. Seems like a relatively low-hanging fruit, at least for addresses. The Icelandic Postal Service makes address names etc. available here: https://www.postur.is/einstaklingar/posthus/postnumer/gagnaskrar/

**Comment by sveinbjornt** [comment]
OK, digging deeper I see Greynir already understands addresses, never mind.

**Comment by sveinbjornt** [comment]
More could be done with this, though. Addresses are not identified as such in the UI for articles, i.e. when you hover over "Ránargata" or "Mjódd". 

Idea for a feature: Identify addresses (esp. Icelandic addresses), show a small map of Iceland on hover with the location marked.

I've also noticed some odd discrepancies. "París" is identified as "höfuðborg Frakklands" but Reykjavík is not identified as "höfuðborg Íslands"

**Comment by vthorsteinsson** [comment]
Good points. Reynir recognizes street names that are marked as such in BÍN (having 'fl' = 'göt'). This is, alas, not a complete list of Icelandic street names and augmenting it with the postur.is data would be a good enhancement. Also, marking street names in the UI would be easy to add - and the map idea is also good one. Any input and help on this is welcome!
