### ISSUE TITLE
Cannot find reynir.fastparser

### ISSUE THREAD

**Issue by BoHuang2018** [vthorsteinsson/Reynir#60]
Hi, 
In the file article.py,  there is 'from reynir.fastparser import Fast_Parser, ParseError, ParseForestDumper'. But there is not the corresponding file 'reynir/fastparser.py'. Was it deleted or got a new name ?

Best regards, 
Bo

**Comment by haukurb** [comment]
Have a look at [ReynirPackage](https://github.com/vthorsteinsson/ReynirPackage). It should be automatically installed from requirements.txt (its module name is reynir).

**Comment by BoHuang2018** [comment]
Thank you, haukurb :-)
