### ISSUE TITLE
Can I use this data for non-profit research?

### ISSUE THREAD

**Issue by davidblurton** [vthorsteinsson/Reynir#9]
Hi Vilhjálmur,

I'm working on a site called [tala.is](https://tala.is) which aims to help people learning Icelandic to look up and correct inflections. 

I'd like to use the data in `Verbs.conf` in tala.is. I haven't been able to find a data set on which cases verbs direct before, so I was very excited to find your project. Here's an example of how the data would be use in tala. I'd be happy to credit your project at the bottom.

<img width="625" alt="screen shot 2015-09-11 at 09 13 26" src="https://cloud.githubusercontent.com/assets/1696979/9811480/16082674-5867-11e5-804a-c6cf4b478b60.png">

I'd be really interested in talking about how our projects could work together to help people learn Icelandic. 

Would you be willing to grant me permission to use the Reynir data in my own project?

**Comment by vthorsteinsson** [comment]
Dear David,

thank you for your interest! You have my permission to use Verbs.conf in
your project. A credit would be appreciated but not required.

Of course the file is provided without representations or warranties of any
kind and there is no guarantee that it is free of errors or omissions.

I will be updating the file regularly with fixes and additions so I
encourage you to fetch new versions once in a while.

Regarding other aspects of Reynir, I am very open to discussion about
co-operation and further development, but I would need to know a bit more
about how the data and code would be used. For instance whether there are
any commercial aspirations down the line, etc.

If you would like to e-mail me directly, my e-mail is vt@extrada.com

Best regards, and good luck with your project,

-- Villi Thorsteinsson
